language: c

compiler:
    - clang
    - gcc

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install libboost-all-dev

script:
    - ./bootstrap && ./configure --enable-test && make && make check

notifications:
  email: false
