language: c

os:
  - linux
  - osx

compiler:
    - clang
    - gcc

before_script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; sudo apt-get update -qq              ; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; sudo apt-get install libboost-all-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update       ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install boost; fi

script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; ./bootstrap && ./configure --enable-test && make && make check; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; ./bootstrap && ./configure_macosx --enable-test && make && make check; fi

notifications:
  email: false
