#!/usr/bin/perl
# Copyright (C) The uecho Authors 2015
#
# This is licensed under BSD-style license, see file COPYING.

use utf8;
use JSON;
use File::Find;

if (@ARGV < 1){
  exit 1;
}
my $mra_root_dir = $ARGV[0];

print<<HEADER;
/******************************************************************
 *
 * uEcho for C
 *
 * Copyright (C) The uecho Authors 2015
 *
 * This is licensed under BSD-style license, see file COPYING.
 *
 * GENERATED FROM manufacturers.pl DO NOT EDIT THIS FILE.
 *
 ******************************************************************/

#include <uecho/std/_database.h>

#define PROP_REQUIRED "required"
#define PROP_MANDATORY "mandatory"
#define PROP_OPTIONAL "optional"

uEchoObject* uecho_standard_object_new(const char* name, int grp_code, int cls_code)
{
  uEchoObject* obj;
  obj = uecho_object_new();
  uecho_object_setname(obj, name);
  obj->code[0] = grp_code;
  obj->code[1] = cls_code;
  return obj;
}

uEchoProperty* uecho_standard_object_property_new(int epc, const char* name, const char* data_type, int data_size, const char* get_rule, const char* set_rule, const char* anno_rule)
{
  uEchoProperty* prop;
  uEchoPropertyAttr attr = uEchoPropertyAttrNone;

  prop = uecho_property_new();
  uecho_property_setcode(prop, epc);
  uecho_property_setname(prop, name);

  if (uecho_streq(get_rule, PROP_REQUIRED) || uecho_streq(get_rule, PROP_REQUIRED))
    attr |= uEchoPropertyAttrReadRequired;
  if (uecho_streq(get_rule, PROP_OPTIONAL))
    attr |= uEchoPropertyAttrRead;
  if (uecho_streq(set_rule, PROP_REQUIRED) || uecho_streq(set_rule, PROP_REQUIRED))
    attr |= uEchoPropertyAttrWriteRequired;
  if (uecho_streq(set_rule, PROP_OPTIONAL))
    attr |= uEchoPropertyAttrWrite;
  if (uecho_streq(anno_rule, PROP_REQUIRED) || uecho_streq(anno_rule, PROP_REQUIRED))
    attr |= uEchoPropertyAttrAnnoRequired;
  if (uecho_streq(anno_rule, PROP_OPTIONAL))
    attr |= uEchoPropertyAttrAnno;
  uecho_property_setattribute(prop, attr);

  return prop;
}

void uecho_database_addstandardobjects(uEchoDatabase* db)
{
  uEchoObject* obj;

HEADER

my $mra_definitions_file = $mra_root_dir . "/mraData/definitions/definitions.json";
open(DEF_JSON_FILE, $mra_definitions_file) or die "$!";
my $def_json_data = join('',<DEF_JSON_FILE>);
close(DEF_JSON_FILE);
my $def_json = decode_json($def_json_data);
my $def_json_root = %{$def_json}{'definitions'};

my @mra_sub_dirs = (
  "/mraData/superClass/",
  "/mraData/nodeProfile/",
  "/mraData/devices/"
);

my @device_json_files;
foreach my $mra_sub_dir(@mra_sub_dirs){
  my $mra_root_dir = $mra_root_dir . $mra_sub_dir;
  find sub {
      my $file = $_;
      my $path = $File::Find::name;
      if(-f $file){
        push(@device_json_files, $path);
      }
  }, $mra_root_dir;
}

foreach my $device_json_file(@device_json_files){
  open(DEV_JSON_FILE, $device_json_file) or die "$!";
  my $device_json_data = join('',<DEV_JSON_FILE>);
  close(DEV_JSON_FILE);
  my $device_json = decode_json($device_json_data);

  my $cls_names = %{$device_json}{'className'};
  my $cls_name = %{$cls_names}{'en'};
  my $grp_cls_code = %{$device_json}{'eoj'};
  my $grp_code = substr($grp_cls_code, 2, 2);
  my $cls_code = substr($grp_cls_code, 4);
  printf("  // %s (0x%s%s)\n", $cls_name, $grp_code, $cls_code);
  printf("  obj = uecho_standard_object_new(\"%s\", 0x%s, 0x%s);\n", $cls_name, $grp_code, $cls_code);

  my $props = %{$device_json}{'elProperties'};
  foreach $prop(@{$props}) {
    my $epc = %{$prop}{'epc'};
    my $names = %{$prop}{'propertyName'};
    my $name = %{$names}{'en'};
    my $rules = %{$prop}{'accessRule'};
    my $get_rule = %{$rules}{'get'};
    my $set_rule = %{$rules}{'set'};
    my $anno_rule = %{$rules}{'inf'};
    my $data = %{$prop}{'data'};
    my $data_type = %{$data}{'type'};
    my $data_size = %{$data}{'size'};
    my $data_ref = %{$data}{'$ref'};
    if (0< length($data_ref)) {
      my @data_refs = split(/\//, $data_ref);
      my $data_ref_len = @data_refs;
      my $data_ref_id = $data_refs[$data_ref_len -1];
      my $prop_def = %{$def_json_root}{$data_ref_id};
      $data_type = %{$prop_def}{'type'};  
      $data_size = %{$prop_def}{'size'};
      my $enums = %{$prop_def}{'enum'};
      if (0 < @data_refs) {
        foreach $enum(@{$enums}) {
          my $edt = %{$enum}{'edt'};
          my $name = %{$enum}{'name'};
          my $descs = %{$enum}{'descriptions'};
          my $desc = %{$descs}{'en'};
          if (0< length($edt)) {
          }
        }
      }
    }
    printf("  uecho_object_addproperty(obj, uecho_standard_object_property_new(%s, \"%s\", \"%s\", %d, \"%s\", \"%s\", \"%s\"));\n",
      $epc,
      $name,
      $data_type,
      $data_size,
      $get_rule,
      $set_rule,
      $anno_rule,
      );
   }
  printf("  uecho_database_addobject(db, obj);\n\n");
}
print<<FOTTER;
}
FOTTER