name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - name: setup
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt update
            sudo apt install -y libboost-all-dev
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew update
            brew install boost
          fi
      - name: configure
        run: ./configure --enable-test --enable-examples
      - name: make
        run: make -j 20
      - name: make check
        run: make check -j 20 || more test/unix/test-suite.log